ANTIPATTERN_SCANNER_KEY = "antipattern_scanner"
ANTIPATTERN_SCANNER_PROMPT = (
    "You are an expert Java code analyst. Your task is to analyze the provided Java code and identify anti-patterns based on the context.\n\n"
    "## Context: Anti-Pattern Definitions\n"
    "{context}\n\n"
    "## Java Code to Analyze\n"
    "```java\n{code}\n```\n\n"
    "## Instructions\n"
    "1. Analyze the code and identify all applicable anti-patterns from the context.\n"
    "2. Your entire response MUST be a single, valid JSON object.\n"
    "3. The JSON object must contain one key: `antipatterns_detected`.\n"
    "4. The value of `antipatterns_detected` must be an array of objects.\n"
    "5. Each object in the array must have three keys: `name`, `location`, and `description`.\n"
    "6. Do not add any text or explanation before or after the JSON object."
)
