"""
State definitions for the antipattern analysis workflow
"""

from typing import TypedDict, Optional


class AgentState(TypedDict):
    """State definition for passing data through the workflow"""
    code: str                    # Code to be analyzed
    context: Optional[str]       # Context retrieved from knowledge base
    antipatterns_scanner_results: Optional[str]
    refactoring_strategy_results: Optional[str]  # Refactoring strategy generated by strategist
    refactored_code: Optional[str]  # Code after refactoring
    code_review_results: Optional[str]  # Code review results
    answer: Optional[str]        # Analysis result
